# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-19 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20171219_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearbit_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ClearbitUser')),
            ],
        ),
    ]
