# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-20 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.TextField(null=True),
        ),
    ]
