# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-20 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
